version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.2.0
  heroku: circleci/heroku@1.0.3

jobs:
  build:
    # ...

  test:
    # ...

  publish:
    # ...

  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: | 
              heroku container:login
              heroku container:push web -a ace-su-devops
              heroku container:release web -a ace-su-devops

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
      - deploy:
          requires:
            - publish
