version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.2.0
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  publish:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          echo "Building Docker image..."
          docker build -t acetay/m4-node-app-for-devops:v1.0.0 .
      - run: |
          echo "Logging in to Docker Hub..."
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
      - docker/push:
          image: acetay/m4-node-app-for-devops
          tag: v1.0.0

    deploy:
      docker:
          - image: cimg/node:16.10
      steps:
          - setup_remote_docker      
          - heroku/install
          - checkout
          - run:
              name: Heroku Container Push
              command: | 
                  heroku container:login
                  heroku container:push web -a ace-su-devops
                  heroku container:release web -a ace-su-devops

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
      - deploy:
          requires:
            - publish
